[phases.setup]
nixPkgs = ['chromium', 'glib', 'nss', 'nspr', 'atk', 'cups', 'dbus', 'gtk3', 'libxkbcommon', 'libXcomposite', 'libXdamage', 'libXfixes', 'libXrandr', 'pango', 'cairo', 'alsa-lib']

[phases.install]
cmds = ['npm ci']

[phases.start]
cmd = 'node index.js'
